name: CI_API

on:
  push:
    branches: [ master ]
    paths:
      - 'api/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x
          
    - name: Install dependencies
      run: yarn
      working-directory: api
      
    - name: Run build
      run: yarn build
      working-directory: api
     
    - name: copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "api/,!api/node_modules"
        target: "~/app/goBarber"
        
    - name: Run production scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/app/goBarber/api
          yarn 
          ./node_modules/.bin/typeorm migration:run
          pm2 restart gobarber-api
